name: ServerMessage
main: ServerMessage\main
version: 1.0.0
api:
  - 3.0.0
  - 4.0.3
author: まっちだよ～(｡･ω･｡)

commands:
  sevm:
    description: §l§eサーバーメッセージ
    usege: /sevm
    permission: op